# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SuperTsao
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog site.
baseurl: "/supertsao" # the subpath of your site, e.g. /blog

url: "https://tsaoyuan.github.io" 
# twitter_username: jekyllrb
github_username: tsaoyuan

author: Tsao-Yuan, Chuang
minimal_mistakes_skin: "air"
# Build settings
# theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-gist
  # Remote theme method
  - jekyll-include-cache


